### ISSUE TITLE
Add Gen6 and Gen7 GPU support (currently provided by Intel's Beignet driver and Mesa's Clover)

### ISSUE THREAD

**Issue by hilga007** [intel/compute-runtime#507]
[Beignet](https://github.com/intel/beignet)  provides OpenCL 1.2 support for Gen6 and Gen7 graphics. Please add these for OpenCL 3.0 (feature level 1.2) support. 

NUCs and Compute Sticks were the "Next Unit of Computing" but the "next" level of OpenCL support and commitment to a platform seems to be lacking

**Comment by antermin** [comment]
Apparently Beignet does not support Gen6 (Sandy Bridge).
Also, from ArchWiki and Mesa source code, apparently Clover only works for AMD (and limited support for iris+clover), while crocus+clover (Gen7 and Gen8LP use crocus) is not supported.

For Gen8LP, there was a feature request, but they [decided](https://github.com/intel/compute-runtime/issues/317#issuecomment-688236589) not to support Gen8LP in NEO Compute Runtime.

Maybe you will also want to check out the [WIP rusticl in Mesa](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15439) and [this comment](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15439#note_1304834).

**Comment by hilga007** [comment]
Who to contact to request beignet simply be merged into mesa for
mesa-opencl which could include its AMD backends + a bringup to modern llvm
for beignet. It is for "outdated" tech (Ivy Bridge, Haswell) but still has
uses.

For example: budget-strapped healthcare organizations could benefit from
some ultrasound imaging that has a huge OpenCL perf boost vs. CPU software
computations. These organizations are stuck on Sandy Bridge / Ivy Bridge /
Haswell, etc.

Thoughts?

**Comment by eero-t** [comment]
Old drivers (in this case beignet) are for supporting old HW.  It does not make sense to have single driver supporting all HW due to differences in how the HW is programmed and what features that HW supports.  At some point there just needs to be clean break to keep driver maintainable.

Btw. It's not just compute where the driver changed between GEN8 <-> GEN9 (beignet -> compute-runtime), also Mesa (i965/crocus -> Iris OpenGL driver) and Media (i965 -> iHD VA-API driver) did that.

And questions about Beignet and Mesa belong to those projects, not here.  Please close this ticket.

**Comment by JablonskiMateusz** [comment]
Hi @hilga007, Gen6 and Gen7 GPUs are supported by beignet driver, please create an issue in their repo https://github.com/intel/beignet.

I'm closing this issue as we are not planning to support these GPUs.

**Comment by hilga007** [comment]
Apparently they no longer are, either, hence asking to have them included
in the supported driver.
