### ISSUE TITLE
Versions >= 22.x fail to build due to CMake Error at cmake/find_metrics.cmake

### ISSUE THREAD

**Issue by tgurr** [intel/compute-runtime#514]
Initially reported at https://github.com/intel/intel-graphics-compiler/issues/233 I was told I have to report the issue here as having metrics support available in igc shouldn't be mandatory and as far as I can see the packages created by GitHub Actions for igc also don't build it due to the same error with protobuf I'm seeing. The actual problem building compute-runtime is a CMake error:

```
CMake Error at cmake/find_metrics.cmake:78 (include_directories):
  include_directories given empty-string as include directory.
Call Stack (most recent call first):
  CMakeLists.txt:369 (include)
```

compute-runtime version I'm trying to build:
* 22.09.22577

Installed dependencies: 
* gmmlib: 22.0.3
* igc: 1.0.10409 (compiled using the "bundled" vc-intrinsics/spirv-headers/spirv-tools)
* llvm: 13.0.1
* opencl-clang: 13.0.0
* os: linux 64bit
* gcc 11.2.0

Complete build log:
[intel-compute-runtime-22.09.22577.log](https://github.com/intel/compute-runtime/files/8223260/intel-compute-runtime-22.09.22577.log)

**Comment by Wallted** [comment]
Hi @tgurr,

Although this fail is actually related to bug in detection, compute-runtime does not need metrics packages to build, as it is designed to fallback to headers located inside our third_party directory. 

The fix for this bug is already on the way, meanwhile the workaround would be to temporarily remove libmd package from your system.

I will notice you when the fix is merged.

**Comment by tgurr** [comment]
Thanks for the hint about libmd, the following workaround to prevent CMake from picking up libmd without having to remove it from my system seems to work for me: `sed -e 's:libmd:libmddonotfindme:g' -i cmake/find_metrics.cmake`

**Comment by Wallted** [comment]
So the main issue is resolved in https://github.com/intel/compute-runtime/commit/a968cb223ea60d476d191a1f61dd4791178aacb4

There is another package conflicting with metrics discovery in ubuntu - `libmd-dev`, which turned out to be installed in your system and then detected . It is not actual metrics discovery package. We temporarily disabled metrics discovery detection in mentioned commit https://github.com/intel/compute-runtime/commit/a968cb223ea60d476d191a1f61dd4791178aacb4. There is no more need for you to use your workaround.

**Comment by ArturHarasimiuk** [comment]
closing issue. @tgurr feel free to reopen or create new issue if you face more problems related to this.
