### ISSUE TITLE
Package version conflict in Ubuntu 22.04

### ISSUE THREAD

**Issue by tatokis** [intel/compute-runtime#538]
The deb packages from the releases can not be installed in Ubuntu 22.04 without removing some already installed packages such as `intel-media-va-driver-non-free` from the jammy repository.

This happens because `intel-media-va-driver-non-free` depends on `libigdgmm12 >= 22.1.2+ds1`, however the libigdgmm12 deb in releases is version `22.1.2` which apt considers to be a downgrade from `22.1.2+ds1`, and thus can not satisfy the dependency for `intel-media-va-driver-non-free`, removing it.
It is also impossible to use `22.1.2+ds1` from the jammy repository, since the rest of the debs from releases (intel-level-zero-gpu, intel-opencl-icd) depend on `libigdgmm12 = 22.1.2`.

This issue did not occur on 21.10.

A solution would be to bump up the epoch to 1 in the debs produced in releases. As such, the new version string for `libigdgmm12` would be `1:22.1.2` which is now considered newer than `22.1.2+ds1`, and can satisfy `intel-media-va-driver-non-free`. The rest of the debs can now depend on `libigdgmm12 = 1:22.1.2` instead.

**Comment by Tamas-Toth-ebola** [comment]
I would have report it now as I have the problem since the release of 22.04.

@tatokis perfectly detailed the problem, originally I just would have dropped my console results:

```shell
dpkg: warning: downgrading libigdgmm12:amd64 from 22.1.2+ds1-1 to 22.1.2
Preparing to unpack libigdgmm12_22.1.2_amd64.deb ...
De-configuring libigdgmm12:i386 (22.1.2+ds1-1), to allow configuration of libigdgmm12:amd64 (22.1.2+ds1-1) ...
Unpacking libigdgmm12:amd64 (22.1.2) over (22.1.2+ds1-1) ...
Setting up intel-igc-core (1.0.11104) ...
Setting up intel-igc-opencl (1.0.11104) ...
dpkg: error processing package libigdgmm12:amd64 (--install):
 package libigdgmm12:amd64 22.1.2 cannot be configured because libigdgmm12:i386 is at a different version (22.1.2+ds1-1)
dpkg: error processing package libigdgmm12:i386 (--install):
 package libigdgmm12:i386 22.1.2+ds1-1 cannot be configured because libigdgmm12:amd64 is at a different version (22.1.2)
dpkg: dependency problems prevent configuration of intel-level-zero-gpu:
 intel-level-zero-gpu depends on libigdgmm12 (= 22.1.2); however:
  Package libigdgmm12:amd64 is not configured yet.

dpkg: error processing package intel-level-zero-gpu (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of intel-opencl-icd:
 intel-opencl-icd depends on libigdgmm12 (= 22.1.2); however:
  Package libigdgmm12:amd64 is not configured yet.

dpkg: error processing package intel-opencl-icd (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of intel-level-zero-gpu-dbgsym:
 intel-level-zero-gpu-dbgsym depends on intel-level-zero-gpu (= 1.3.23063); however:
  Package intel-level-zero-gpu is not configured yet.

dpkg: error processing package intel-level-zero-gpu-dbgsym (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of intel-opencl-icd-dbgsym:
 intel-opencl-icd-dbgsym depends on intel-opencl-icd (= 22.18.23063); however:
  Package intel-opencl-icd is not configured yet.

dpkg: error processing package intel-opencl-icd-dbgsym (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Errors were encountered while processing:
 libigdgmm12:amd64
 libigdgmm12:i386
 intel-level-zero-gpu
 intel-opencl-icd
 intel-level-zero-gpu-dbgsym
 intel-opencl-icd-dbgsym
```

**Comment by tatokis** [comment]
@Tamas-Toth-ebola that is a slightly different issue, which most likely can't be resolved easily as there are no 32 bit debs provided in releases. If you don't care about 32 bit support, you can run `sudo apt remove libigdgmm12:i386`.

**Comment by Tamas-Toth-ebola** [comment]
Thank you for the correction!

If I'm right ubuntu nowadays out-of-box does not 'deliver' 32 bit packages, so what we see at me could be the result of Steam, what just something side-way thingie because of my daughter. For me 32 bit packages really not needed, but Steam could miss them.

But stepping back from the theory sadly I got myself in something like dependency loop after my latest attempt to install OpenCL Git release so I had some hard minutes until at the end I could clean the broken background of it.

I had to `dpkg --purge --force-all` all the relevant packages as without it there were continuous dependency warnings and which `apt` could not handle _(at least I could not deal with it)_.

_(`apt remove libigdgmm12:i386` could not remove the package because strangely it had different versions of the package for 32bit and for 64bit. 32bit version was the newer one from Ubuntu repo, but the 64bit was a broken one from the Git installation. Honestly 'I do not know' what happened but as we can see my last post the installation started with `dpkg: warning: downgrading libigdgmm12:amd64 from 22.1.2+ds1-1 to 22.1.2` message which basically covers the later problem...)_

Now seems I have a working dependendency background again so for a while I think I leave it alone :smile:

**Comment by eero-t** [comment]
@tjaalton, could you comment on what would be the best solution for this?

**Comment by tjaalton** [comment]
wait until you build with libigdgmm >= 22.1.2

bumping the epoch is a one-way train, there's no going back to distro packages without "downgrading" packages manually

**Comment by eero-t** [comment]
Ok, so all of:
* media-driver package(s) in Ubuntu
* IGC / compute-runtime package(s) in Ubuntu
* Ubuntu packages provided by media-driver project
* Ubuntu packages provided by IGC / compute-runtime projects

Need to co-operate in using ">=" (instead of "=") version deps for the library dependencies they share, to avoid any of them triggering similar problem.  I assume this is already true of the packages in Ubuntu itself.

**Comment by thetick1234567890** [comment]
Yes I am also stuck on some older compute runtime packages as I need the VA driver for video hardware acceleration.  Seems like not breaking other Intel delivered packages on the latest Ubuntu should be an easy post build step in your CI/CD pipeline.

**Comment by ArturHarasimiuk** [comment]
as of 22.21.23269 intel-opencl-icd and intel-level-zero-gpu dependencies were updated to allow newer version, i.e. we use `>=` operator. However, please keep in mind that newer version of gmmlib than this from release may not work correctly if you decide to pick newer in future.
_This change may be subject of revert in future if we find any issues._

**Comment by thetick1234567890** [comment]
Latest release is working fine with updated Jammy, 5.18 kernel and last night mesa build.

**Comment by eero-t** [comment]
@tatokis Could you close this issue now that it's fixed?    (Or report how/why latest release is still not working for you)

**Comment by bruor** [comment]
I am on 22.04, was previously unable to install.   After this was released I was able to "apt-get update" and "apt-get install intel-opencl-icd" without issue.

**Comment by tatokis** [comment]
@eero-t Apologies, I haven't had time to test. I'll give it a try soon and close the issue if it's fixed.

**Comment by eero-t** [comment]
> I'll give it a try soon and close the issue if it's fixed.

@tatokis any updates?

**Comment by tatokis** [comment]
I have just confirmed that the packages can now be correctly installed. Thank you and apologies for the extremely late response.

**Comment by eero-t** [comment]
Great to hear that it works, and thanks for verifying/closing!
