### ISSUE TITLE
Typo in `ZE_FABRIC_VERTEX_EXP_TYPE_SUBEVICE` breaks the build

### ISSUE THREAD

**Issue by ziguana** [intel/compute-runtime#608]
https://github.com/intel/compute-runtime/search?q=ZE_FABRIC_VERTEX_EXP_TYPE_SUBEVICE

I only uncovered this now when building the latest `level-zero` release. How was this typo even checked in? Does nothing really build this code?

**Comment by jandres742** [comment]
hi @ziguana . Yes, sorry about that. This was a typo from the specification. Because of that, we needed to wait for specification and loader to update the headers with the typo fixed. This has been done now in https://github.com/intel/compute-runtime/commit/dce17d319f91b39806b2cd39b6eecd5c5cff2a68.

thanks for bringing this into our attention.
