### ISSUE TITLE
A critical bug happened with HDR Mapping with opencl

### ISSUE THREAD

**Issue by ShCby** [intel/compute-runtime#643]
I am using proxmox ve host and using Ubuntu 22.04 LTS VM.

UHD770 enables SR-IOV.

when they use the decoding function using opencl in ubuntu, it have these video errors.

![227777769-b56c123a-cd73-49a3-9101-d6cfa5f8a3a7 (1)](https://github.com/intel/compute-runtime/assets/17939484/1cc2553d-fa9e-4d5e-9d56-9fbb61f5baa8)

**Comment by nyanmisaka** [comment]
It's a Plex exclusive issue and should be reported here.
See also https://forums.plex.tv/t/movie-corruption-when-plex-decodes-4k-hdr/834529

**Comment by ShCby** [comment]
> It's a Plex exclusive issue and should not be reported here. See also https://forums.plex.tv/t/movie-corruption-when-plex-decodes-4k-hdr/834529

You can see more information here.
https://github.com/strongtz/i915-sriov-dkms/issues/57

**Comment by nyanmisaka** [comment]
@ShCby As far as I know, intel hasn't officially supported SR-IOV in mainline kernels. So It makes sense that they won't test [media-driver](https://github.com/intel/media-driver) and [compute-runtime](https://github.com/intel/compute-runtime) with third-party modified DKMS in such use case.

The broken image seems to be caused by a mismatched DRM format modifier that used to describe the memory layout.
You can turn to https://github.com/intel/media-driver for help.
