### ISSUE TITLE
Documentation/Clarification Regarding Level Zero interaction with compute-runtime

### ISSUE THREAD

**Issue by pvelesko** [intel/compute-runtime#685]
not sure where to ask this - just wanted to get some clarification on how does level zero loader interact with compute-runtime? Specifically, why doesn't Level Zero loader state compute-runtime as a dependency nor provide flags for specifying the runtime install path?

**Comment by eero-t** [comment]
"compute-runtime" project provides backends both for OpenCL and Level-Zero, but names of packages for those backends are not named "compute-runtime" (package specs can mention it as source project though).

The dependencies go the other way round, because loader package cannot know which HW the host on which it is installed, will have, i.e. what backend would be relevant one.  For more info on package deps, see: https://github.com/intel/compute-runtime/issues/470

**Comment by eero-t** [comment]
> Specifically, why doesn't Level Zero loader state compute-runtime as a dependency

Another reason is that plain loader allows compute programs to be built.  Backend is needed only when one wants to run the built program, and these actions may happen on different machines.

> nor provide flags for specifying the runtime install path?

Backend registers itself for the loader when installed (using ICD Json file). Same as how it works with OpenCL.
